# Use an official Node.js image as the base image
FROM mongo-express:latest

ENV ME_CONFIG_MONGODB_ENABLE_ADMIN='true'       
ENV ME_CONFIG_MONGODB_ADMINUSERNAME="admin"
ENV ME_CONFIG_MONGODB_ADMINPASSWORD="admin"
ENV ME_CONFIG_MONGODB_PORT='27017'
ENV ME_CONFIG_MONGODB_SERVER='mongodb'
ENV ME_CONFIG_OPTIONS_EDITORTHEME='lucario'
ENV ME_CONFIG_BASICAUTH_USERNAME='admin'
ENV ME_CONFIG_BASICAUTH_PASSWORD='admin'
ENV ME_CONFIG_MONGODB_URL='mongodb://admin:admin@mongodb:27017/'

# Expose Mongo Express port
EXPOSE 8081

# Command to start Mongo Express
CMD ["mongo-express", "-u", "admin", "-p", "admin", "--host", "mongo", "--port", "27017"]