FROM docker.elastic.co/kibana/kibana:7.15.0

# Configurar variables de entorno de Kibana si es necesario
# ENV KIBANA_HOST=localhost
# ENV KIBANA_PORT=5601

# Puedes agregar configuraciones personalizadas si es necesario
# COPY kibana.yml /usr/share/kibana/config/kibana.yml
EXPOSE 5601
CMD ["kibana"]
